version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: social_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1434:1433"
    volumes:
      - db_data:/var/opt/mssql

  connectly:
    container_name: connectly_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080" 
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db,1433;Initial Catalog=ConnectlyDB;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True

volumes:
  db_data: